const Product = require("../../domain/entities/product.entity");
const { NotFoundError } = require("../../domain/errors/custom-error");

class ProductService {
  constructor(productRepository) {
    this.productRepository = productRepository;
  }

  async getAllProducts() {
    return this.productRepository.getAll();
  }

  async getProductById(id) {
    const product = await this.productRepository.getById(id);

    if (!product) {
      throw new NotFoundError("Product not found");
    }

    return product;
  }

  async createProduct(productData) {
    const productEntity = new Product(
      null, // ID is null because it will be generated by the database
      productData.name,
      productData.description,
      productData.price,
      productData.stock,
      productData.category,
      productData.imageUrl
    );

    return this.productRepository.create(productEntity);
  }

  async updateProduct(id, productData) {
    const productEntity = new Product(
      id,
      productData.name,
      productData.description,
      productData.price,
      productData.stock,
      productData.category,
      productData.imageUrl
    );

    const updatedProduct = await this.productRepository.update(
      id,
      productEntity
    );

    if (!updatedProduct) {
      throw new NotFoundError("Product not found");
    }

    return updatedProduct;
  }

  async deleteProduct(id) {
    const deletedProduct = await this.productRepository.delete(id);

    if (!deletedProduct) {
      throw new NotFoundError("Product not found");
    }

    return;
  }
}

module.exports = ProductService;
